apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight
  labels:
    app: flight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
        - name: flight
          image: "kimgyeongjun/flight:0702"
          ports:
            - containerPort: 8080
          env:
          - name: FLIGHT_NAME
            valueFrom:
              configMapKeyRef:
                name: config-dev
                key: FLIGHT_NAME
          - name: FLIGHT_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: config-dev
                key: FLIGHT_LOG_LEVEL
          volumeMounts:
            - name: k8s-my
          resources:
            requests:
              cpu: "200m" 
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
